name: Deploy to Prod

on:
  push:
    branches:
      - master
      - feature/**

jobs:
  docker-build-and-push:
    uses: ./.github/workflows/.reusable-docker-build-and-push.yml

  deploy-to-prod:
    needs: [docker-build-and-push]
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Deploy
        env:
          INNER_CIRCLE_PROD_MAIL_SMTP_PORT: ${{ secrets.INNER_CIRCLE_PROD_MAIL_SMTP_PORT }}
          INNER_CIRCLE_PROD_MAIL_SMTP_HOST: ${{ secrets.DEV_MAIL_HOST }}
          INNER_CIRCLE_PROD_MAIL_SMTP_FROM_EMAIL: ${{ secrets.INNER_CIRCLE_PROD_MAIL_SMTP_FROM_EMAIL }}
          INNER_CIRCLE_PROD_MAIL_SMTP_FROM_PASSWORD: ${{ secrets.INNER_CIRCLE_PROD_MAIL_SMTP_FROM_PASSWORD }}
        run: |
            helmfile cache cleanup && helmfile apply --suppress-diff --namespace "${{ secrets.INNER_CIRCLE_PROD_NAMESPACE }}" -f Api/ci/helmfile.yaml \
            --state-values-set image.tag="sha-${{ github.sha }}" \
            --state-values-set ingress.hostname="${{ secrets.INNER_CIRCLE_PROD_HOSTNAME }}" \ 
            --state-values-set extraSecretEnvVars.MailSmtpOptions__Port="$INNER_CIRCLE_PROD_MAIL_SMTP_PORT" \
            --state-values-set extraSecretEnvVars.MailSmtpOptions__Host="$INNER_CIRCLE_PROD_MAIL_SMTP_HOST" \
            --state-values-set extraSecretEnvVars.MailSmtpOptions__FromEmail="$INNER_CIRCLE_PROD_MAIL_SMTP_FROM_EMAIL" \
            --state-values-set extraSecretEnvVars.MailSmtpOptions__FromPassword="$INNER_CIRCLE_PROD_MAIL_SMTP_FROM_PASSWORD" \
            --state-values-set extraConfigMapEnvVars.ASPNETCORE_ENVIRONMENT=Development > /dev/null 2>&1
